# Use goreman to run `go install github.com/mattn/goreman@latest`
raftexample1: ./raftexample --id 1 --cluster http://127.0.0.1:12377,http://127.0.0.1:22377,http://127.0.0.1:32377 --port 12388 --dataDir ../data
raftexample2: ./raftexample --id 2 --cluster http://127.0.0.1:12377,http://127.0.0.1:22377,http://127.0.0.1:32377 --port 22388 --dataDir ../data
raftexample3: ./raftexample --id 3 --cluster http://127.0.0.1:12377,http://127.0.0.1:22377,http://127.0.0.1:32377 --port 32388 --dataDir ../data
